swiss_club = Club.create(name: "Swiss Club")
Hiker.create(first_name: "Bob", last_name: "Cobb", email: "bob@net.com", club: swiss_club, username: "bobcobb", password_digest: "pass123")
Hiker.create(first_name: "Hal", last_name: "Hope", email: "hal@info.com", club: swiss_club, username: "halhope", password_digest: "pass456")

Mountain.create(name: "Mount Blanc", country: "France", height: 4810)
Mountain.create(name: "Monte Rosa", country: "Switzerland", height: 4634)
Mountain.create(name: "Dom", country: "Switzerland", height: 4545)
Mountain.create(name: "Weisshorn", country: "Switzerland", height: 4505)
Mountain.create(name: "Taschhorn", country: "Switzerland", height: 4491)
Mountain.create(name: "Matterhorn", country: "Switzerland", height: 4478)
Mountain.create(name: "Jungfrau", country: "Switzerland", height: 4158)
Mountain.create(name: "Monch", country: "Switzerland", height: 4099)
Mountain.create(name: "Grand Paradiso", country: "Italy", height: 4061)
Mountain.create(name: "Grossglockner", country: "Austria", height: 3798)
Mountain.create(name: "Mulhacen", country: "Spain", height: 3479)
Mountain.create(name: "Zugspitze", country: "Germany", height: 2962)
Mountain.create(name: "Musala", country: "Bulgaria", height: 2925)
Mountain.create(name: "Mount Olympus", country: "Greece", height: 2919)
Mountain.create(name: "Triglav", country: "Slovenia", height: 2864)
Mountain.create(name: "Mount Korab", country: "Albania", height: 2764)
Mountain.create(name: "Gerlachovsky stit", country: "Slovakia", height: 2655)
Mountain.create(name: "Moldoveanu Peak", country: "Romania", height: 2544)
Mountain.create(name: "Galdhopiggen", country: "Norway", height: 2469)
Mountain.create(name: "Ben Nevis", country: "Scotland", height: 1344)
